# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: git://github.com/Bahjat/pre-commit-golang
    rev: master
    hooks:
    -   id: go-fmt-import
    -   id: go-vet
    -   id: go-lint
    -   id: go-unit-tests
    -   id: go-err-check

