[server]
address = ":8082"
api_prefix = "/api/v1/"
api_spec_file = "openapi.json"

[groups]
path = "groups_config.yaml"

[content]
path = "rules-content"

[metrics]
namespace = "insights_content_service"

[logging]
debug = true
